//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Book_Store_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        
        public int id { get; set; }

        [Required]
        [Display(Name ="Title")]
        public string title { get; set; }

        public Nullable<int> AuthorId { get; set; }

        [Required]
        [Display(Name = "Publication Year")]
        public int publicationYear { get; set; }

        [Required]
        [Display(Name = "Price")]
        public decimal price { get; set; }
    
        public virtual Author Author { get; set; }
    }
}
